server {
  listen 80;
  root /usr/share/nginx/html;
  location = /index.html {
    add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
  }
  location / {
    try_files $uri /index.html;
    add_header Cache-Control "no-cache" always;
  }
  location /sales-api/ { proxy_pass http://sales-service:8081/api/; }
  location /ta-api/ { proxy_pass http://ta-service:8082/api/; }
}
