import {verifyGlobalCatalogHttp} from './global-catalog-http.js';
import {verifyHoldingsHttp} from './holdings-http.js';
import {verifyHoldingsApplyRace} from './holdings-apply-race.js';
import {verifyCaseResultReviews} from './case-result-reviews.js';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createHoldingsReturnRepository} from '../../src/holdings-return.js';
import {createReturnParsingRepository} from '../../src/return-parsing.js';
import {createReturnParsingService} from '../../../case-api/src/return-parsing.js';
import {buildDataFile,dataFileName} from '../../../platform-protocol/src/index.js';
export async function verifyHoldingsSync({db,transaction,token,workspaceId,channelId,confirmations,trade,returned04,createCase,stage,generate,parse}) {
 const holdings=createHoldingsReturnRepository({transaction});
 const scope={chatPublicId:crypto.randomUUID(),casePublicId:crypto.randomUUID()};
 const [chat]=await db.execute(`INSERT INTO case_chats(public_id,workspace_id,title) VALUES (?,?,'05独立同步')`,[scope.chatPublicId,workspaceId]);
 const [c]=await db.execute(`INSERT INTO cases(public_id,workspace_id,chat_id,title,status) VALUES (?,?,?,'05独立同步','SOP_LOCKED')`,[scope.casePublicId,workspaceId,chat.insertId]);
 const step={stepId:'r05',roundId:'holdings',direction:'RECEIVE',fileType:'05',businessTime:{kind:'RELATIVE',value:'用户上传TA对账'},required:true,dependsOn:[]};
 await db.execute(`INSERT INTO case_sop_versions(workspace_id,chat_id,case_id,version_number,status,plan_json,locked_at)
   VALUES (?,?,?,1,'LOCKED',?,NOW())`,[workspaceId,chat.insertId,c.insertId,JSON.stringify({exchangePlan:{status:'READY',openQuestions:[],steps:[step]}})]);
 let sequence=710;
 const record={TransactionAccountID:trade.TransactionAccountID,TAAccountID:trade.TAAccountID,DistributorCode:'306',BranchCode:'306',FundCode:trade.FundCode,ShareClass:trade.ShareClass,
   DetailFlag:'0',WholeFlag:'0',TransactionCfmDate:'20261007',TotalVolOfDistributorInTA:'450.00',AvailableVol:'420.00',TotalFrozenVol:'30.00'};
 const upload=async(records,date='20261007')=>{
   const options={creator:'27',receiver:'306',date,version:'22',fileType:'05',sequence:++sequence};
   const file={fileName:dataFileName(options),base64:buildDataFile({...options,records}).toString('base64')};
   return {result:await holdings.parse(token,{...scope,channelId,exchangeStepId:'r05',files:[file]}),file};
 };
 await verifyHoldingsHttp({db,holdings,confirmations,token,workspaceId,channelId,scope,chatId:chat.insertId,caseId:c.insertId,record});
 const before=await confirmations.salesData(token);
 const one=await upload([record,{...record,DetailFlag:'1'},{...record,DetailFlag:'A'}]);
 assert.deepEqual(await confirmations.salesData(token),before);
 const applied=await holdings.apply(token,{...scope,parseId:one.result.parseId});
 assert.deepEqual(applied.results.map(r=>r.status),['SYNCED','DETAIL_ONLY','FUND_SUMMARY_ONLY']);
 let sales=await confirmations.salesData(token);
 assert.equal(sales.holdings[0].totalVolume,'450.00');assert.equal(sales.holdings[0].availableVolume,'420.00');
 assert.equal((await holdings.apply(token,{...scope,parseId:one.result.parseId})).duplicate,true);
 assert.equal((await holdings.parse(token,{...scope,channelId,files:[one.file]})).duplicate,true);
 const twoSteps={exchangePlan:{status:'READY',openQuestions:[],steps:[step,{...step,stepId:'r05_2',roundId:'second'}]}};
 await db.execute('UPDATE case_sop_versions SET plan_json=? WHERE workspace_id=? AND chat_id=? AND case_id=?',[JSON.stringify(twoSteps),workspaceId,chat.insertId,c.insertId]);
 await assert.rejects(holdings.parse(token,{...scope,channelId,exchangeStepId:'r05_2',files:[one.file]}),{code:'EXCHANGE_STEP_CONFLICT'});
 const alias={...one.file,fileName:one.file.fileName.replace('_711.TXT','_709.TXT')};
 await assert.rejects(holdings.parse(token,{...scope,channelId,exchangeStepId:'r05_2',files:[alias]}),{code:'EXCHANGE_STEP_CONFLICT'});
 twoSteps.exchangePlan.steps=[step];
 await db.execute('UPDATE case_sop_versions SET plan_json=? WHERE workspace_id=? AND chat_id=? AND case_id=?',[JSON.stringify(twoSteps),workspaceId,chat.insertId,c.insertId]);
 assert.deepEqual(await confirmations.salesData(token),sales);
 const bad=await upload([{...record,TransactionCfmDate:'20261008',TotalVolOfDistributorInTA:'500.00'},{...record,TransactionAccountID:'UNKNOWN',TransactionCfmDate:'20261008'}],'20261008');
 await assert.rejects(holdings.apply(token,{...scope,parseId:bad.result.parseId}),{code:'SALES_ACCOUNT_UNCONFIRMED'});
 assert.deepEqual(await confirmations.salesData(token),sales);
 const old=await upload([{...record,TransactionCfmDate:'20261006'}],'20261006');
 await assert.rejects(holdings.apply(token,{...scope,parseId:old.result.parseId}),{code:'STALE_HOLDING_SNAPSHOT'});
 const conflict=await upload([{...record,TotalVolOfDistributorInTA:'451.00'}]);
 await assert.rejects(holdings.apply(token,{...scope,parseId:conflict.result.parseId}),{code:'HOLDING_SNAPSHOT_CONFLICT'});
 await assert.rejects(holdings.apply(token,{chatPublicId:scope.chatPublicId,casePublicId:crypto.randomUUID(),parseId:one.result.parseId}),{code:'CASE_NOT_FOUND'});
 // 05 may arrive before an additional 04. The transaction is still recorded, but its covered balance isn't added twice.
 const late=await createCase(false);
 await confirmations.selectAccount(token,{...late.scope,accountPublicId:sales.accounts[0].publicId});
 const lateData=await confirmations.applicationData(token,late.scope,late.data);
 const lateTrade={...trade,AppSheetSerialNo:'LATEAFTER05'};
 const app=await stage(late.scope,lateData,'03',lateTrade);
 const batch=await generate(late.scope,lateTrade,app);
 await confirmations.delivery(token,{...late.scope,batchPublicId:batch,exchangeStepId:'s03_1'});
 const lateReturn=await parse(late.scope,batch,'04',[{...returned04,AppSheetSerialNo:lateTrade.AppSheetSerialNo}],799);
 await confirmations.apply(token,{...late.scope,parseId:lateReturn.parseId,recordIndexes:[0],exchangeStepId:'r04_1'});
 const covered=await confirmations.salesData(token);
 assert.equal(covered.transactions.length,sales.transactions.length+1);
 assert.equal(covered.holdings[0].totalVolume,'450.00');
 const future=await createCase(false);
 await confirmations.selectAccount(token,{...future.scope,accountPublicId:sales.accounts[0].publicId});
 const futureData=await confirmations.applicationData(token,future.scope,future.data);
 const [[planRow]]=await db.execute(`SELECT s.id,s.plan_json FROM case_sop_versions s JOIN cases k ON k.workspace_id=s.workspace_id AND k.chat_id=s.chat_id AND k.id=s.case_id WHERE k.public_id=? AND s.status='LOCKED'`,[future.scope.casePublicId]);
 const futurePlan=typeof planRow.plan_json==='string'?JSON.parse(planRow.plan_json):planRow.plan_json;
 futurePlan.exchangePlan.steps.forEach(step=>step.businessTime.value='20261008');
 await db.execute('UPDATE case_sop_versions SET plan_json=? WHERE id=?',[JSON.stringify(futurePlan),planRow.id]);
 const futureTrade={...trade,AppSheetSerialNo:'FUTUREAFTER05',TransactionDate:'20261008'};
 const futureApp=await stage(future.scope,futureData,'03',futureTrade);
 const futureBatch=await generate(future.scope,futureTrade,futureApp);
 await confirmations.delivery(token,{...future.scope,batchPublicId:futureBatch,exchangeStepId:'s03_1'});
 const returnOptions={creator:'27',receiver:'306',date:'20261008',version:'22',fileType:'04',sequence:798};
 const futureParse=await createReturnParsingService({repository:createReturnParsingRepository({transaction})}).parse(token,{...future.scope,batchPublicId:futureBatch,expectedType:'04',exchangeStepId:'r04_1',files:[{
   fileName:dataFileName(returnOptions),base64:buildDataFile({...returnOptions,records:[{...returned04,...futureTrade,BusinessCode:'122',TransactionCfmDate:'20261008'}]}).toString('base64')}]});
 if(process.env.CASE_DB_NAME?.startsWith('ta_case_agent_testholdingsrace')){
  const racing05=await upload([record]);
  await db.execute('UPDATE sales_confirmed_holdings SET snapshot_date=NULL,snapshot_total=NULL,snapshot_available=NULL,snapshot_frozen=NULL,snapshot_parse_id=NULL WHERE workspace_id=? AND fund_code=?',[workspaceId,trade.FundCode]);
  await verifyHoldingsApplyRace({db,token,scope,parseId:racing05.result.parseId,channelId,confirmations,returnInput:{...future.scope,parseId:futureParse.parseId,recordIndexes:[0],exchangeStepId:'r04_1'}});
 }else await confirmations.apply(token,{...future.scope,parseId:futureParse.parseId,recordIndexes:[0],exchangeStepId:'r04_1'});
 const advanced=await confirmations.salesData(token);
 assert.equal(advanced.holdings[0].totalVolume,'650.00');assert.equal(advanced.holdings[0].availableVolume,null);assert.equal(advanced.holdings[0].frozenVolume,null);
 const same=await upload([record]);
 assert.equal((await holdings.apply(token,{...scope,parseId:same.result.parseId})).results[0].totalVolume,'650.00');
 assert.deepEqual(await confirmations.salesData(token),advanced);
 const newer=await upload([{...record,TransactionCfmDate:'20261008',TotalVolOfDistributorInTA:'700.00'}],'20261008');
 await holdings.apply(token,{...scope,parseId:newer.result.parseId});
 assert.equal((await confirmations.salesData(token)).holdings[0].totalVolume,'700.00');
 const zeros=await upload([{...record,TotalVolOfDistributorInTA:'0.00',AvailableVol:'0.00',TotalFrozenVol:'0.00',TransactionCfmDate:'20261008',FundCode:'000002'}],'20261008');
 await holdings.apply(token,{...scope,parseId:zeros.result.parseId});
 sales=await confirmations.salesData(token);
 assert.equal(sales.holdings.find(h=>h.fundCode===trade.FundCode).totalVolume,'700.00');
 assert.equal(sales.holdings.find(h=>h.fundCode==='000002').totalVolume,'0.00');
 const empty=await upload([],'20261009');assert.equal((await holdings.apply(token,{...scope,parseId:empty.result.parseId})).businessApplied,false);
 assert.deepEqual(await confirmations.salesData(token),sales);
 await verifyCaseResultReviews({db,transaction,token,scope,workspaceId});
 await verifyGlobalCatalogHttp({db,transaction,token,workspaceId});
 const [raw]=await db.execute('SELECT raw_bytes FROM case_holdings_return_files WHERE workspace_id=? AND parse_id=?',[workspaceId,zeros.result.parseId]);
 assert.ok(raw[0].raw_bytes.length>0);
 assert.equal((await holdings.read(token,scope)).steps.length,1);
 await db.execute('UPDATE case_holdings_return_files SET raw_bytes=? WHERE workspace_id=? AND parse_id=?',[Buffer.from('damaged'),workspaceId,zeros.result.parseId]);
 await assert.rejects(holdings.apply(token,{...scope,parseId:zeros.result.parseId}),{code:'RETURN_SOURCE_INVALID'});
 assert.deepEqual(await confirmations.salesData(token),sales);
}
