import { TRANSACTION_BUSINESSES } from './businesses.js';

const f = (name, type, length, scale = 0) => ({ name, type, length, scale });

export const LEGACY_FILE_DEFINITIONS = {
  '01': [
    f('Address', 'C', 300), f('AppSheetSerialNo', 'C', 24),
    f('CertificateType', 'C', 3), f('CertificateNo', 'C', 40),
    f('InvestorName', 'C', 200), f('TransactionDate', 'A', 8),
    f('TransactionTime', 'A', 6), f('IndividualOrInstitution', 'A', 1),
    f('PostCode', 'A', 6), f('TransactionAccountID', 'C', 17),
    f('DistributorCode', 'C', 9), f('BusinessCode', 'C', 3),
    f('InvestorsBirthday', 'A', 8), f('DepositAcct', 'C', 40),
    f('RegionCode', 'A', 4), f('EmailAddress', 'C', 40),
    f('VocationCode', 'C', 5), f('AnnualIncome', 'N', 16),
    f('MobileTelNo', 'C', 40), f('BranchCode', 'C', 9),
    f('Sex', 'A', 1), f('TAAccountID', 'C', 12), f('TradingMethod', 'C', 8),
    f('MultiAcctFlag', 'A', 1), f('AcctNameOfInvestorInClearingAgency', 'C', 200),
    f('AcctNoOfInvestorInClearingAgency', 'C', 40), f('ClearingAgency', 'C', 20),
    f('Nationality', 'C', 3), f('CertValidDate', 'A', 8),
    f('ClientRiskRate', 'C', 1), f('AcceptMethod', 'C', 1),
    f('IPAddress', 'C', 40)
  ],
  '02': [
    f('AppSheetSerialNo', 'C', 24), f('TransactionCfmDate', 'A', 8),
    f('ReturnCode', 'A', 4), f('TransactionAccountID', 'C', 17),
    f('DistributorCode', 'C', 9), f('BusinessCode', 'C', 3),
    f('TAAccountID', 'C', 12), f('MultiAcctFlag', 'A', 1),
    f('TASerialNO', 'C', 20), f('TransactionDate', 'A', 8),
    f('TransactionTime', 'A', 6), f('BranchCode', 'C', 9),
    f('FromTAFlag', 'A', 1), f('RegionCode', 'A', 4),
    f('ErrorDetail', 'C', 60)
  ],
  '03': [
    f('AppSheetSerialNo', 'C', 24), f('FundCode', 'C', 6),
    f('LargeRedemptionFlag', 'A', 1),
    f('TransactionDate', 'A', 8), f('TransactionTime', 'A', 6),
    f('TransactionAccountID', 'C', 17), f('DistributorCode', 'C', 9),
    f('ApplicationVol', 'N', 16, 2), f('ApplicationAmount', 'N', 16, 2),
    f('BusinessCode', 'C', 3),
    f('TAAccountID', 'C', 12), f('DiscountRateOfCommission', 'N', 5, 4),
    f('DepositAcct', 'C', 40), f('RegionCode', 'A', 4),
    f('CurrencyType', 'A', 3), f('BranchCode', 'C', 9),
    f('OriginalAppSheetNo', 'C', 24), f('IndividualOrInstitution', 'A', 1),
    f('OriginalSerialNo', 'C', 20), f('TargetTransactionAccountID', 'C', 17),
    f('TargetRegionCode', 'A', 4), f('DefDividendMethod', 'A', 1),
    f('FrozenCause', 'A', 1), f('ShareClass', 'C', 1),
    f('ChargeType', 'C', 1), f('IPAddress', 'C', 40)
  ],
  '04': [
    f('AppSheetSerialNo', 'C', 24), f('TransactionCfmDate', 'A', 8),
    f('CurrencyType', 'A', 3), f('ConfirmedVol', 'N', 16, 2),
    f('ConfirmedAmount', 'N', 16, 2), f('FundCode', 'C', 6),
    f('LargeRedemptionFlag', 'A', 1),
    f('TransactionDate', 'A', 8), f('TransactionTime', 'A', 6),
    f('ReturnCode', 'A', 4), f('TransactionAccountID', 'C', 17),
    f('DistributorCode', 'C', 9), f('ApplicationVol', 'N', 16, 2),
    f('ApplicationAmount', 'N', 16, 2),
    f('BusinessCode', 'C', 3), f('TAAccountID', 'C', 12),
    f('TASerialNO', 'C', 20), f('BusinessFinishFlag', 'C', 1),
    f('DiscountRateOfCommission', 'N', 5, 4), f('DepositAcct', 'C', 40),
    f('RegionCode', 'A', 4), f('DownLoaddate', 'A', 8),
    f('Charge', 'N', 16, 2), f('AgencyFee', 'N', 16, 2),
    f('NAV', 'N', 16, 8), f('BranchCode', 'C', 9),
    f('OriginalAppSheetNo', 'C', 24), f('OtherFee1', 'N', 16, 2),
    f('OriginalSerialNo', 'C', 20), f('TargetTransactionAccountID', 'C', 17),
    f('TargetRegionCode', 'A', 4), f('DefDividendMethod', 'A', 1),
    f('FrozenCause', 'A', 1), f('IndividualOrInstitution', 'A', 1),
    f('RateFee', 'N', 9, 8),
    f('TransferFee', 'N', 16, 2), f('FromTAFlag', 'A', 1),
    f('ShareClass', 'C', 1), f('TotalTransFee', 'N', 16, 2),
    f('FeeCalculator', 'A', 1), f('ShareRegisterDate', 'A', 8),
    f('FundVolBalance', 'N', 16, 2), f('BreachFee', 'N', 16, 2),
    f('BreachFeeBackToFund', 'N', 16, 2), f('PunishFee', 'N', 16, 2),
    f('AchievementPay', 'N', 16, 2), f('AchievementCompen', 'N', 16, 2),
    f('ErrorDetail', 'C', 60)
  ],
  '05': [
    f('AvailableVol', 'N', 16, 2), f('TotalVolOfDistributorInTA', 'N', 16, 2),
    f('TransactionCfmDate', 'A', 8), f('FundCode', 'C', 6),
    f('TransactionAccountID', 'C', 17), f('DistributorCode', 'C', 9),
    f('TAAccountID', 'C', 12), f('TotalFrozenVol', 'N', 16, 2),
    f('BranchCode', 'C', 9), f('TASerialNO', 'C', 20),
    f('ShareClass', 'C', 1), f('DetailFlag', 'C', 1),
    f('AccountStatus', 'A', 1), f('ShareRegisterDate', 'A', 8),
    f('SourceType', 'C', 1), f('WholeFlag', 'C', 1)
  ],
  '07': [
    f('FundName', 'C', 200), f('TotalFundVol', 'N', 16, 2),
    f('FundCode', 'C', 6), f('FundStatus', 'C', 1),
    f('NAV', 'N', 16, 8), f('UpdateDate', 'A', 8),
    f('NetValueType', 'C', 1), f('AccumulativeNAV', 'N', 16, 8),
    f('ConvertStatus', 'C', 1), f('PeriodicStatus', 'C', 1),
    f('TransferAgencyStatus', 'C', 1), f('FundSize', 'N', 16, 2),
    f('CurrencyType', 'A', 3), f('AnnouncFlag', 'C', 1),
    f('MinBidsAmountByIndi', 'N', 16, 2), f('MinAppBidsAmountByIndi', 'N', 16, 2),
    f('CollectFeeType', 'C', 1), f('NextTradeDate', 'A', 8),
    f('FundType', 'C', 2), f('FundTypeName', 'C', 30),
    f('FundManagerName', 'C', 100), f('IndiMaxPurchase', 'N', 16, 2),
    f('IndiDayMaxSumBuy', 'N', 16, 2)
  ]
};

export const FILE_DEFINITIONS = {
  '01': [
    f('Address', 'C', 300), f('InstReprIDCode', 'C', 40), f('InstReprIDType', 'C', 3),
    f('InstReprName', 'C', 60), f('AppSheetSerialNo', 'C', 24), f('CertificateType', 'C', 3),
    f('CertificateNo', 'C', 40), f('InvestorName', 'C', 200), f('TransactionDate', 'A', 8),
    f('TransactionTime', 'A', 6), f('IndividualOrInstitution', 'A', 1), f('PostCode', 'A', 6),
    f('TransactorCertNo', 'C', 40), f('TransactorCertType', 'C', 3), f('TransactorName', 'C', 60),
    f('TransactionAccountID', 'C', 17), f('DistributorCode', 'C', 9), f('BusinessCode', 'C', 3),
    f('AcctNoOfFMInClearingAgency', 'C', 28), f('AcctNameOfFMInClearingAgency', 'C', 60), f('ClearingAgencyCode', 'A', 9),
    f('InvestorsBirthday', 'A', 8), f('DepositAcct', 'C', 40), f('RegionCode', 'A', 4),
    f('EducationLevel', 'C', 3), f('EmailAddress', 'C', 40), f('FaxNo', 'C', 40),
    f('VocationCode', 'C', 5), f('HomeTelNo', 'C', 40), f('AnnualIncome', 'N', 16),
    f('MobileTelNo', 'C', 40), f('BranchCode', 'C', 9), f('OfficeTelNo', 'C', 40),
    f('AccountAbbr', 'C', 20), f('ConfidentialDocumentCode', 'C', 8), f('Sex', 'A', 1),
    f('SHSecuritiesAccountID', 'C', 10), f('SZSecuritiesAccountID', 'C', 10), f('TAAccountID', 'C', 12),
    f('TelNo', 'C', 40), f('TradingMethod', 'C', 8), f('MinorFlag', 'C', 1),
    f('DeliverType', 'C', 1), f('TransactorIDType', 'C', 1), f('AccountCardID', 'C', 8),
    f('MultiAcctFlag', 'A', 1), f('TargetTransactionAccountID', 'C', 17), f('AcctNameOfInvestorInClearingAgency', 'C', 200),
    f('AcctNoOfInvestorInClearingAgency', 'C', 40), f('ClearingAgency', 'C', 20), f('DeliverWay', 'C', 8),
    f('Nationality', 'C', 3), f('NetNo', 'C', 9), f('Broker', 'C', 12),
    f('CorpName', 'C', 200), f('CertValidDate', 'A', 8), f('InstTranCertValidDate', 'A', 8),
    f('InstReprCertValidDate', 'A', 8), f('ClientRiskRate', 'C', 1), f('MarriageStatus', 'C', 1),
    f('FamilyNum', 'N', 2), f('Penates', 'N', 16, 2), f('MediaHobby', 'C', 1),
    f('InstitutionType', 'C', 3), f('EnglishFirstName', 'C', 20), f('EnglishFamliyName', 'C', 20),
    f('Vocation', 'C', 4), f('CorpoProperty', 'C', 2), f('StaffNum', 'N', 16, 2),
    f('Hobbytype', 'C', 2), f('Province', 'C', 6), f('City', 'C', 6),
    f('County', 'C', 6), f('CommendPerson', 'C', 40), f('CommendPersonType', 'C', 1),
    f('AcceptMethod', 'C', 1), f('FrozenCause', 'A', 1), f('FreezingDeadline', 'A', 8),
    f('OriginalSerialNo', 'C', 20), f('OriginalAppSheetNo', 'C', 24), f('Specification', 'C', 60),
    f('InvestorProCode', 'C', 30), f('AuxCertType', 'C', 3), f('AuxCertCode', 'C', 40),
    f('AuxCertValidDate', 'C', 8), f('IPAddress', 'C', 40), f('MACAddress', 'C', 20),
    f('IMEI', 'C', 20), f('UUID', 'C', 32)
  ],
  '02': [
    f('AppSheetSerialNo', 'C', 24), f('TransactionCfmDate', 'A', 8), f('ReturnCode', 'A', 4),
    f('TransactionAccountID', 'C', 17), f('DistributorCode', 'C', 9), f('BusinessCode', 'C', 3),
    f('TAAccountID', 'C', 12), f('MultiAcctFlag', 'A', 1), f('TASerialNO', 'C', 20),
    f('TransactionDate', 'A', 8), f('TransactionTime', 'A', 6), f('BranchCode', 'C', 9),
    f('FromTAFlag', 'A', 1), f('CertificateType', 'C', 3), f('CertificateNo', 'C', 40),
    f('InvestorName', 'C', 200), f('IndividualOrInstitution', 'A', 1), f('AccountAbbr', 'C', 20),
    f('AccountCardID', 'C', 8), f('RegionCode', 'A', 4), f('TargetTransactionAccountID', 'C', 17),
    f('NetNo', 'C', 9), f('Specification', 'C', 60), f('CustomerNo', 'C', 12),
    f('FrozenCause', 'A', 1), f('FreezingDeadline', 'A', 8), f('ErrorDetail', 'C', 60)
  ],
  '03': [
    f('AppSheetSerialNo', 'C', 24), f('FundCode', 'C', 6), f('LargeRedemptionFlag', 'A', 1),
    f('TransactionDate', 'A', 8), f('TransactionTime', 'A', 6), f('TransactionAccountID', 'C', 17),
    f('DistributorCode', 'C', 9), f('ApplicationVol', 'N', 16, 2), f('ApplicationAmount', 'N', 16, 2),
    f('BusinessCode', 'C', 3), f('TAAccountID', 'C', 12), f('DiscountRateOfCommission', 'N', 5, 4),
    f('DepositAcct', 'C', 40), f('RegionCode', 'A', 4), f('CurrencyType', 'A', 3),
    f('BranchCode', 'C', 9), f('OriginalAppSheetNo', 'C', 24), f('OriginalSubsDate', 'A', 8),
    f('IndividualOrInstitution', 'A', 1), f('ValidPeriod', 'N', 2), f('DaysRedemptionInAdvance', 'N', 5),
    f('RedemptionDateInAdvance', 'A', 8), f('OriginalSerialNo', 'C', 20), f('DateOfPeriodicSubs', 'A', 8),
    f('TASerialNO', 'C', 20), f('TermOfPeriodicSubs', 'N', 5), f('FutureBuyDate', 'A', 8),
    f('TargetDistributorCode', 'C', 9), f('Charge', 'N', 16, 2), f('TargetBranchCode', 'C', 9),
    f('TargetTransactionAccountID', 'C', 17), f('TargetRegionCode', 'A', 4), f('DividendRatio', 'N', 16, 2),
    f('Specification', 'C', 60), f('CodeOfTargetFund', 'C', 6), f('TotalBackendLoad', 'N', 16, 2),
    f('ShareClass', 'C', 1), f('OriginalCfmDate', 'A', 8), f('DetailFlag', 'C', 1),
    f('OriginalAppDate', 'A', 8), f('DefDividendMethod', 'A', 1), f('FrozenCause', 'A', 1),
    f('FreezingDeadline', 'A', 8), f('VarietyCodeOfPeriodicSubs', 'C', 5), f('SerialNoOfPeriodicSubs', 'C', 5),
    f('RationType', 'C', 1), f('TargetTAAccountID', 'C', 12), f('TargetRegistrarCode', 'C', 18),
    f('NetNo', 'C', 9), f('CustomerNo', 'C', 12), f('TargetShareType', 'C', 1),
    f('RationProtocolNo', 'C', 20), f('BeginDateOfPeriodicSubs', 'A', 8), f('EndDateOfPeriodicSubs', 'A', 8),
    f('SendDayOfPeriodicSubs', 'N', 2), f('Broker', 'C', 12), f('SalesPromotion', 'C', 3),
    f('AcceptMethod', 'C', 1), f('ForceRedemptionType', 'C', 1), f('TakeIncomeFlag', 'C', 1),
    f('PurposeOfPeSubs', 'C', 40), f('FrequencyOfPeSubs', 'N', 5), f('PeriodSubTimeUnit', 'C', 1),
    f('BatchNumOfPeSubs', 'N', 16, 2), f('CapitalMode', 'C', 2), f('DetailCapticalMode', 'C', 2),
    f('BackenloadDiscount', 'N', 5, 4), f('CombineNum', 'C', 6), f('FutureSubscribeDate', 'A', 8),
    f('TradingMethod', 'C', 8), f('LargeBuyFlag', 'A', 1), f('ChargeType', 'C', 1),
    f('SpecifyRateFee', 'N', 9, 8), f('SpecifyFee', 'N', 16, 2), f('TransferReason', 'C', 3),
    f('IPAddress', 'C', 40), f('MACAddress', 'C', 20), f('IMEI', 'C', 20),
    f('UUID', 'C', 32), f('AcctNameOfInvestorInClearingAgency', 'C', 200), f('AcctNoOfInvestorInClearingAgency', 'C', 40),
    f('ClearingAgency', 'C', 20)
  ],
  '04': [
    f('AppSheetSerialNo', 'C', 24), f('TransactionCfmDate', 'A', 8), f('CurrencyType', 'A', 3),
    f('ConfirmedVol', 'N', 16, 2), f('ConfirmedAmount', 'N', 16, 2), f('FundCode', 'C', 6),
    f('LargeRedemptionFlag', 'A', 1), f('TransactionDate', 'A', 8), f('TransactionTime', 'A', 6),
    f('ReturnCode', 'A', 4), f('TransactionAccountID', 'C', 17), f('DistributorCode', 'C', 9),
    f('ApplicationVol', 'N', 16, 2), f('ApplicationAmount', 'N', 16, 2), f('BusinessCode', 'C', 3),
    f('TAAccountID', 'C', 12), f('TASerialNO', 'C', 20), f('BusinessFinishFlag', 'C', 1),
    f('DiscountRateOfCommission', 'N', 5, 4), f('DepositAcct', 'C', 40), f('RegionCode', 'A', 4),
    f('DownLoaddate', 'A', 8), f('Charge', 'N', 16, 2), f('AgencyFee', 'N', 16, 2),
    f('NAV', 'N', 16, 8), f('BranchCode', 'C', 9), f('OriginalAppSheetNo', 'C', 24),
    f('OriginalSubsDate', 'A', 8), f('OtherFee1', 'N', 16, 2), f('IndividualOrInstitution', 'A', 1),
    f('RedemptionDateInAdvance', 'A', 8), f('StampDuty', 'N', 16, 2), f('ValidPeriod', 'N', 2),
    f('RateFee', 'N', 9, 8), f('TotalBackendLoad', 'N', 16, 2), f('OriginalSerialNo', 'C', 20),
    f('Specification', 'C', 60), f('DateOfPeriodicSubs', 'A', 8), f('TargetDistributorCode', 'C', 9),
    f('TargetBranchCode', 'C', 9), f('TargetTransactionAccountID', 'C', 17), f('TargetRegionCode', 'A', 4),
    f('TransferDirection', 'A', 1), f('DefDividendMethod', 'A', 1), f('DividendRatio', 'N', 16, 2),
    f('Interest', 'N', 16, 2), f('VolumeByInterest', 'N', 16, 2), f('InterestTax', 'N', 16, 2),
    f('TradingPrice', 'N', 16, 8), f('FreezingDeadline', 'A', 8), f('FrozenCause', 'A', 1),
    f('Tax', 'N', 16, 2), f('TargetNAV', 'N', 16, 8), f('TargetFundPrice', 'N', 16, 8),
    f('CfmVolOfTargetFund', 'N', 16, 2), f('MinFee', 'N', 16, 2), f('OtherFee2', 'N', 16, 2),
    f('OriginalAppDate', 'A', 8), f('TransferFee', 'N', 16, 2), f('FromTAFlag', 'A', 1),
    f('ShareClass', 'C', 1), f('DetailFlag', 'C', 1), f('RedemptionInAdvanceFlag', 'A', 1),
    f('FrozenMethod', 'A', 1), f('OriginalCfmDate', 'A', 8), f('RedemptionReason', 'A', 1),
    f('CodeOfTargetFund', 'C', 6), f('TotalTransFee', 'N', 16, 2), f('VarietyCodeOfPeriodicSubs', 'C', 5),
    f('SerialNoOfPeriodicSubs', 'C', 5), f('RationType', 'C', 1), f('TargetTAAccountID', 'C', 12),
    f('TargetRegistrarCode', 'C', 18), f('NetNo', 'C', 9), f('CustomerNo', 'C', 12),
    f('TargetShareType', 'C', 1), f('RationProtocolNo', 'C', 20), f('BeginDateOfPeriodicSubs', 'A', 8),
    f('EndDateOfPeriodicSubs', 'A', 8), f('SendDayOfPeriodicSubs', 'N', 2), f('Broker', 'C', 12),
    f('SalesPromotion', 'C', 3), f('AcceptMethod', 'C', 1), f('ForceRedemptionType', 'C', 1),
    f('AlternationDate', 'A', 8), f('TakeIncomeFlag', 'C', 1), f('PurposeOfPeSubs', 'C', 40),
    f('FrequencyOfPeSubs', 'N', 5), f('PeriodSubTimeUnit', 'C', 1), f('BatchNumOfPeSubs', 'N', 16, 2),
    f('CapitalMode', 'C', 2), f('DetailCapticalMode', 'C', 2), f('BackenloadDiscount', 'N', 5, 4),
    f('CombineNum', 'C', 6), f('RefundAmount', 'N', 16, 2), f('SalePercent', 'N', 16, 8),
    f('ManagerRealRatio', 'N', 7, 4), f('ChangeFee', 'N', 16, 2), f('RecuperateFee', 'N', 16, 2),
    f('AchievementPay', 'N', 16, 2), f('AchievementCompen', 'N', 16, 2), f('SharesAdjustmentFlag', 'C', 1),
    f('GeneralTASerialNO', 'C', 20), f('UndistributeMonetaryIncome', 'N', 16, 2), f('UndistributeMonetaryIncomeFlag', 'C', 1),
    f('BreachFee', 'N', 16, 2), f('BreachFeeBackToFund', 'N', 16, 2), f('PunishFee', 'N', 16, 2),
    f('TradingMethod', 'C', 8), f('ChangeAgencyFee', 'N', 16, 2), f('RecuperateAgencyFee', 'N', 16, 2),
    f('ErrorDetail', 'C', 60), f('LargeBuyFlag', 'A', 1), f('RaiseInterest', 'N', 16, 2),
    f('FeeCalculator', 'A', 1), f('ShareRegisterDate', 'A', 8), f('TotalFrozenVol', 'N', 16, 2),
    f('FundVolBalance', 'N', 16, 2), f('FrozenBalance', 'N', 16, 2), f('FutureSubscribeDate', 'A', 8),
    f('TransferDateThroughClearingAgency', 'A', 8), f('TransferReason', 'C', 3)
  ],
  '05': [
    f('AvailableVol', 'N', 16, 2), f('TotalVolOfDistributorInTA', 'N', 16, 2), f('TransactionCfmDate', 'A', 8),
    f('FundCode', 'C', 6), f('TransactionAccountID', 'C', 17), f('DistributorCode', 'C', 9),
    f('TAAccountID', 'C', 12), f('TotalFrozenVol', 'N', 16, 2), f('BranchCode', 'C', 9),
    f('TASerialNO', 'C', 20), f('TotalBackendLoadVol', 'N', 16, 2), f('ShareClass', 'C', 1),
    f('DetailFlag', 'C', 1), f('AccountStatus', 'C', 1), f('ShareRegisterDate', 'A', 8),
    f('UndistributeMonetaryIncome', 'N', 16, 2), f('UndistributeMonetaryIncomeFlag', 'C', 1), f('GuaranteedAmount', 'N', 16, 2),
    f('SourceType', 'C', 1), f('DefDividendMethod', 'A', 1), f('NewIncome', 'N', 16, 2),
    f('NewIncomeFlag', 'C', 1), f('WholeFlag', 'C', 1)
  ],
  '07': [
    f('FundName', 'C', 200), f('TotalFundVol', 'N', 16, 2), f('FundCode', 'C', 6),
    f('FundStatus', 'C', 1), f('NAV', 'N', 16, 8), f('UpdateDate', 'A', 8),
    f('NetValueType', 'C', 1), f('AccumulativeNAV', 'N', 16, 8), f('ConvertStatus', 'C', 1),
    f('PeriodicStatus', 'C', 1), f('TransferAgencyStatus', 'C', 1), f('FundSize', 'N', 16, 2),
    f('CurrencyType', 'A', 3), f('AnnouncFlag', 'C', 1), f('DefDividendMethod', 'A', 1),
    f('InstAppSubsAmnt', 'N', 16, 2), f('InstAppSubsVol', 'N', 16, 2), f('MinAmountByInst', 'N', 16, 2),
    f('MinVolByInst', 'N', 16, 2), f('CustodianCode', 'C', 18), f('AmountOfPeriodicSubs', 'N', 16, 2),
    f('DateOfPeriodicSubs', 'A', 8), f('MaxRedemptionVol', 'N', 16, 2), f('MinAccountBalance', 'N', 16, 2),
    f('IPOStartDate', 'A', 8), f('IPOEndDate', 'A', 8), f('FundManagerCode', 'C', 18),
    f('IndiAppSubsVol', 'N', 16, 2), f('IndiAppSubsAmount', 'N', 16, 2), f('MinSubsVolByIndi', 'N', 16, 2),
    f('MinSubsAmountByIndi', 'N', 16, 2), f('RegistrarCode', 'C', 18), f('FundSponsor', 'C', 18),
    f('TradingPrice', 'N', 16, 8), f('FaceValue', 'N', 16, 8), f('DividentDate', 'A', 8),
    f('RegistrationDate', 'A', 8), f('XRDate', 'A', 8), f('MaxSubsVolByIndi', 'N', 16, 2),
    f('MaxSubsAmountByIndi', 'N', 16, 2), f('MaxSubsVolByInst', 'N', 16, 2), f('MaxSubsAmountByInst', 'N', 16, 2),
    f('UnitSubsVolByIndi', 'N', 16, 2), f('UnitSubsAmountByIndi', 'N', 16, 2), f('UnitSubsVolByInst', 'N', 16, 2),
    f('UnitSubsAmountByInst', 'N', 16, 2), f('MinBidsAmountByIndi', 'N', 16, 2), f('MinBidsAmountByInst', 'N', 16, 2),
    f('MinAppBidsAmountByIndi', 'N', 16, 2), f('MinAppBidsAmountByInst', 'N', 16, 2), f('MinRedemptionVol', 'N', 16, 2),
    f('MinInterconvertVol', 'N', 16, 2), f('IssueTypeByIndi', 'C', 1), f('IssueTypeByInst', 'C', 1),
    f('SubsType', 'C', 1), f('CollectFeeType', 'C', 1), f('NextTradeDate', 'A', 8),
    f('ValueLine', 'N', 7, 2), f('TotalDivident', 'N', 16, 8), f('FundIncome', 'N', 8, 5),
    f('FundIncomeFlag', 'C', 1), f('Yield', 'N', 8, 5), f('YieldFlag', 'C', 1),
    f('GuaranteedNAV', 'N', 16, 8), f('FundYearIncomeRate', 'N', 8, 5), f('FundYearIncomeRateFlag', 'C', 1),
    f('IndiMaxPurchase', 'N', 16, 2), f('InstMaxPurchase', 'N', 16, 2), f('IndiDayMaxSumBuy', 'N', 16, 2),
    f('InstDayMaxSumBuy', 'N', 16, 2), f('IndiDayMaxSumRedeem', 'N', 16, 2), f('InstDayMaxSumRedeem', 'N', 16, 2),
    f('IndiMaxRedeem', 'N', 16, 2), f('InstMaxRedeem', 'N', 16, 2), f('FundDayIncomeFlag', 'C', 1),
    f('FundDayIncome', 'N', 16, 2), f('AllowBreachRedempt', 'C', 1), f('FundType', 'C', 2),
    f('FundTypeName', 'C', 30), f('RegistrarName', 'C', 100), f('FundManagerName', 'C', 100),
    f('FundServerTel', 'C', 40), f('FundInternetAddress', 'C', 200), f('MainFundCode', 'C', 6),
    f('SideBagFlag', 'C', 3), f('NextTradeEndDate', 'A', 8)
  ]
};

// “必填/条件必填/选填”是发送前编辑器使用的协议元数据。条件必填字段的
// condition 文案用于教学说明；具体业务校验仍由发送端完成。
export const FIELD_REQUIREMENTS = {
  '01': {
    required: ['AppSheetSerialNo','CertificateType','CertificateNo','InvestorName','TransactionDate','TransactionTime','IndividualOrInstitution','TransactionAccountID','DistributorCode','BusinessCode','BranchCode'],
    requiredByBusiness: {
      '002': ['TAAccountID'], '003': ['TAAccountID'], '004': ['TAAccountID'],
      '005': ['TAAccountID'], '006': ['TAAccountID'], '007': ['TAAccountID'],
      '008': ['TAAccountID'], '009': ['TAAccountID']
    },
    conditional: {
      DepositAcct: '采用银行卡结算时必填',
      AcctNameOfInvestorInClearingAgency: '填写结算账户时必填',
      AcctNoOfInvestorInClearingAgency: '填写结算账户时必填',
      ClearingAgency: '填写结算账户时必填',
      CertValidDate: '证件存在有效期时必填',
      MobileTelNo: '以手机作为联系方式时必填'
    }
  },
  '03': {
    required: [],
    requiredByBusiness: Object.fromEntries(Object.entries(TRANSACTION_BUSINESSES).map(([code,item])=>[code,item.required03])),
    conditional: {
      DepositAcct: '采用银行卡扣款时必填',
      DiscountRateOfCommission: '销售机构参与费率折扣时必填',
      ShareClass: '基金存在多份额类别时必填',
      ChargeType: '基金支持前后端收费时必填'
    }
  },
  '04': {
    required: [],
    requiredByBusiness: Object.fromEntries(Object.values(TRANSACTION_BUSINESSES).filter(item=>item.confirmationCode).map(item=>[item.confirmationCode,item.required04]))
  }
};

export const RETURN_CODES = {
  '0000': '成功', '0013': '账户已存在，开户失败', '0100': '证件号码错误',
  '0101': '证件号码重复', '0104': '销售人交易基金账号非法', '0108': '证件类型非法',
  '0117': '开户网点非法', '0139': '申请单编号非法', '0411': '重复开户',
  '0422': '当天多次开户（交易账号重复）', '0201': '基金代码非法',
  '0205': '申请金额非法', '0228': '基金停止申购', '0241': '基金账户状态不正常',
  '0316': '基金账户不存在', '0363': '基金账号信息未作改动',
  '0317': '基金账户状态不允许当前操作', '0318': '交易账户不存在',
  '0319': '交易账户已存在', '0320': '最后一个交易账户不能撤销',
  '0321': '基金账户存在份额，不能销户',
  '9999': '人工模拟失败'
};
