import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import mysql from 'mysql2/promise';
import {migrationConfig} from '../src/migrate.js';
import {createCaseRepository,sessionTokenHash} from '../src/index.js';
import {createChatLifecycleRepository} from '../src/chat-lifecycle.js';
import {createApplicationPreparationRepository} from '../src/application-preparation.js';
import {createHoldingsReturnRepository} from '../src/holdings-return.js';
import {createReturnConfirmationRepository} from '../src/return-confirmation.js';
import {createCaseResultRepository} from '../src/case-result.js';

test('MySQL: close preserves statuses, requires human verdicts, freezes old writes and links idempotent fresh runs',
 {skip:process.env.CASE_CONFIRMATION_MYSQL!=='1'},async()=>{
 const db=await mysql.createConnection(migrationConfig());
 try{
  await db.beginTransaction();
  const token=crypto.randomBytes(32).toString('base64url'),id=crypto.randomUUID();
  const [user]=await db.execute(`INSERT INTO platform_users(public_id,email,password_hash,display_name) VALUES (?,?,?,'生命周期测试')`,[id,id+'@example.invalid','synthetic']);
  const [ws]=await db.execute('INSERT INTO workspaces(public_id,owner_user_id) VALUES (?,?)',[crypto.randomUUID(),user.insertId]);
  await db.execute('INSERT INTO platform_sessions(token_hash,user_id,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))',[sessionTokenHash(token),user.insertId]);
  let n=0;const transaction=async action=>{const name='life_'+ ++n;await db.query('SAVEPOINT '+name);try{return await action(db);}catch(e){await db.query('ROLLBACK TO SAVEPOINT '+name);throw e;}};
  const repo=createCaseRepository({transaction}),life=createChatLifecycleRepository({transaction});
  const chat=await repo.createChat(token,'多Case'),a=await repo.createCase(token,chat.publicId,'A'),b=await repo.createCase(token,chat.publicId,'B');
  const input={chatPublicId:chat.publicId};
  await assert.rejects(life.close(token,{...input,mode:'NORMAL'}),{code:'CHAT_CASES_INCOMPLETE'});
  await assert.rejects(life.close(token,{...input,mode:'FORCE',reason:' '}),{code:'INVALID_REASON'});
  assert.equal((await life.read(token,input)).cases.length,2);
  await life.close(token,{...input,mode:'FORCE',reason:'暂停本轮'});
  assert.equal((await life.close(token,{...input,mode:'FORCE',reason:'暂停本轮'})).duplicate,true);
  await assert.rejects(life.close(token,{...input,mode:'FORCE',reason:'不同原因'}),{code:'CHAT_CLOSURE_CONFLICT'});
  assert.deepEqual((await life.read(token,input)).cases.map(c=>c.status),['DISCUSSING','DISCUSSING']);
  assert.equal((await repo.readCaseDiscussion(token,chat.publicId,a.publicId)).turns.length,0);
  await assert.rejects(repo.createCase(token,chat.publicId,'C'),{code:'CHAT_CLOSED'});
  await assert.rejects(repo.beginCaseDiscussionTurn(token,chat.publicId,a.publicId,{expectedRevision:0,userInput:'继续'}),{code:'CHAT_CLOSED'});
  const scoped={chatPublicId:chat.publicId,casePublicId:a.publicId};
  await assert.rejects(createApplicationPreparationRepository({transaction}).save(token,{...scoped,revision:0,state:{}}),{code:'DATA_NOT_CONFIRMED'});
  await assert.rejects(createReturnConfirmationRepository({transaction}).delivery(token,{...scoped,batchPublicId:crypto.randomUUID()}),{code:'CASE_NOT_WRITABLE'});
  await assert.rejects(createHoldingsReturnRepository({transaction}).apply(token,{...scoped,parseId:'1',exchangeStepId:'receive05'}),{code:'CASE_NOT_WRITABLE'});
  await assert.rejects(createCaseResultRepository({transaction}).snapshot(token,scoped),{code:'CASE_NOT_WRITABLE'});
  const restart={...input,requestId:crypto.randomUUID(),reason:'空白再跑',confirmPreserveFormalData:true};
  const fresh=await life.newRun(token,restart);assert.equal(fresh.formalDataPreserved,true);
  assert.equal((await life.read(token,{chatPublicId:fresh.chatPublicId})).cases.length,0);
  assert.equal((await life.newRun(token,restart)).chatPublicId,fresh.chatPublicId);
  await assert.rejects(life.newRun(token,{...restart,reason:'另一个请求'}),{code:'RUN_REQUEST_CONFLICT'});
  await assert.rejects(life.newRun(token,{...restart,requestId:crypto.randomUUID(),confirmPreserveFormalData:false}),{code:'PRESERVATION_CONFIRMATION_REQUIRED'});
  const [[scope]]=await db.execute('SELECT id FROM case_chats WHERE workspace_id=? AND public_id=?',[ws.insertId,chat.publicId]);
  await db.execute("UPDATE cases SET status='FAIL' WHERE workspace_id=? AND chat_id=?",[ws.insertId,scope.id]);
  await assert.rejects(life.retest(token,{...input,casePublicId:a.publicId,requestId:crypto.randomUUID(),reason:'修复后'}),{code:'RETEST_REQUIRES_FAIL'});
  const normal=await repo.createChat(token,'正常结束'),c=await repo.createCase(token,normal.publicId,'已审核');
  const [[owned]]=await db.execute('SELECT k.id,k.chat_id FROM cases k WHERE k.workspace_id=? AND k.public_id=?',[ws.insertId,c.publicId]);
  await db.execute("UPDATE cases SET status='FAIL' WHERE id=?",[owned.id]);
  await db.execute(`INSERT INTO case_sop_versions(workspace_id,chat_id,case_id,version_number,plan_json) VALUES (?,?,?,1,'{}')`,[ws.insertId,owned.chat_id,owned.id]);
  await db.execute(`INSERT INTO case_result_reviews(workspace_id,chat_id,case_id,plan_version,evidence_sha256,evidence_json,suggestion_json,actor_user_id,final_verdict,confirmation_reason,confirmed_by_user_id,confirmed_at) VALUES (?,?,?,1,?,'{}','{}',?,'FAIL','人工失败',?,NOW())`,[ws.insertId,owned.chat_id,owned.id,'0'.repeat(64),user.insertId,user.insertId]);
  await assert.rejects(life.close(token,{chatPublicId:normal.publicId,mode:'NORMAL'}),{code:'CHAT_CASES_INCOMPLETE'});
  const retryInput={chatPublicId:normal.publicId,casePublicId:c.publicId,requestId:crypto.randomUUID(),reason:'修复后复测'};
  const retry=await life.retest(token,retryInput);assert.ok(retry.casePublicId);assert.equal(retry.chatPublicId,normal.publicId);
  assert.equal((await life.retest(token,retryInput)).duplicate,true);
  const discussion=await repo.readCaseDiscussion(token,retry.chatPublicId,retry.casePublicId);
  assert.equal(discussion.sourceContext.casePublicId,c.publicId);assert.equal(discussion.sourceContext.humanFailureReason,'人工失败');assert.equal(discussion.sourceContext.contextIsReadOnly,true);assert.equal(discussion.turns.length,0);
  await assert.rejects(repo.readCaseDiscussion(token,fresh.chatPublicId,retry.casePublicId),{code:'CASE_NOT_FOUND'});
  const target=await life.read(token,{chatPublicId:retry.chatPublicId});assert.equal(target.cases[1].status,'DISCUSSING');assert.equal(target.cases[1].predecessorCasePublicId,c.publicId);assert.equal(target.links[0].sourceCasePublicId,c.publicId);
  assert.equal((await life.read(token,{chatPublicId:normal.publicId})).cases[0].status,'FAIL');
  await assert.rejects(life.retest(token,{...retryInput,requestId:crypto.randomUUID()}),{code:'RETEST_ALREADY_EXISTS'});
  await life.close(token,{chatPublicId:normal.publicId,mode:'FORCE',reason:'后续未完成'});
  await assert.rejects(life.retest(token,{...retryInput,requestId:crypto.randomUUID()}),{code:'CHAT_CLOSED'});
  const otherToken=crypto.randomBytes(32).toString('base64url'),otherId=crypto.randomUUID();
  const [other]=await db.execute(`INSERT INTO platform_users(public_id,email,password_hash,display_name) VALUES (?,?,?,'其他用户')`,[otherId,otherId+'@example.invalid','synthetic']);
  await db.execute('INSERT INTO workspaces(public_id,owner_user_id) VALUES (?,?)',[crypto.randomUUID(),other.insertId]);
  await db.execute('INSERT INTO platform_sessions(token_hash,user_id,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))',[sessionTokenHash(otherToken),other.insertId]);
  await assert.rejects(life.read(otherToken,input),{code:'CHAT_NOT_FOUND'});
 }finally{await db.rollback();await db.end();}
});
