import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createGlobalFileCatalog} from '../src/global-file-catalog.js';
const token='a'.repeat(43),bytes=Buffer.from([0xff,0,10,13]);
function fixture(file){const calls=[];return {calls,repo:createGlobalFileCatalog({transaction:fn=>fn({execute:async(sql,values)=>{calls.push({sql,values});if(sql.includes('FROM platform_sessions'))return [[{workspace_id:37,user_id:8}]];if(sql.includes('COUNT(*)'))return [[{total:0}]];if(sql.includes('f.raw_bytes,f.content_sha256'))return [[file]];return [[]];}})})};}
test('catalog includes outbound, 02/04 originals and 05 originals within current workspace',async()=>{const f=fixture();await f.repo.listFiles(token,{q:"a%'"});for(const c of f.calls.slice(1)){assert.deepEqual(c.values.slice(0,3),[37,37,37]);assert.match(c.sql,/case_return_parse_files/);assert.match(c.sql,/case_holdings_return_files/);assert.equal((c.sql.match(/f.workspace_id=\?/g)||[]).length,3);assert.ok(c.values.slice(3).every(v=>v==="%a\\%'%"));assert.doesNotMatch(c.sql,/SELECT[^]*raw_bytes AS/);}});
test('every download checks workspace and parent/case scope and preserves exact bytes',async()=>{for(const kind of ['outbound','return','holdings']){const f=fixture({file_name:'OFD_TEST.TXT',raw_bytes:bytes,content_sha256:crypto.createHash('sha256').update(bytes).digest('hex')});const r=await f.repo.downloadFile(token,{kind,id:'9',fileName:'OFD_TEST.TXT'});assert.deepEqual(r.rawBytes,bytes);assert.deepEqual(f.calls[1].values,[37,'9','OFD_TEST.TXT']);assert.match(f.calls[1].sql,/JOIN case_chats/);if(kind!=='outbound')assert.match(f.calls[1].sql,/JOIN cases/);}});
test('unavailable or corrupt originals cannot produce a successful download',async()=>{await assert.rejects(fixture().repo.downloadFile(token,{kind:'outbound',id:9,fileName:'OFD.TXT'}),{code:'FILE_NOT_FOUND'});await assert.rejects(fixture({file_name:'OFD.TXT',raw_bytes:bytes,content_sha256:'broken'}).repo.downloadFile(token,{kind:'return',id:9,fileName:'OFD.TXT'}),{code:'FILE_SOURCE_INVALID'});});
test('malformed locators and header/path injection are rejected before database access',async()=>{for(const input of [{kind:'sql',id:'9',fileName:'OFD.TXT'},{kind:'return',id:'-1',fileName:'OFD.TXT'},{kind:'holdings',id:'9',fileName:'../x'},{kind:'outbound',id:'9',fileName:'x\r\nX:a'}]){const f=fixture();await assert.rejects(f.repo.downloadFile(token,input),{code:'INVALID_FILE'});assert.equal(f.calls.length,0);}});
test('only identical named inbound bytes with a same-workspace parsed archive are suppressed',async()=>{const f=fixture();await f.repo.listFiles(token);for(const c of f.calls.slice(1)){assert.match(c.sql,/f.direction='OUTBOUND' OR \(NOT EXISTS/);assert.match(c.sql,/NOT EXISTS \(SELECT 1 FROM case_return_parse_files r WHERE r.workspace_id=f.workspace_id AND r.file_name=f.file_name AND r.content_sha256=f.content_sha256\)/);assert.match(c.sql,/NOT EXISTS \(SELECT 1 FROM case_holdings_return_files r WHERE r.workspace_id=f.workspace_id AND r.file_name=f.file_name AND r.content_sha256=f.content_sha256\)/);}});
