import test from 'node:test';
import assert from 'node:assert/strict';
import {createGlobalDataCatalog,catalogOptions} from '../src/global-data-catalog.js';
const token='a'.repeat(43);
function fixture(rows=[]){const calls=[];return {calls,repo:createGlobalDataCatalog({transaction:async fn=>fn({execute:async(sql,values)=>{calls.push({sql,values});if(sql.includes('FROM platform_sessions'))return [[{workspace_id:37,user_id:8}]];if(sql.includes('COUNT(*)'))return [[{total:rows.length}]];return [rows];}})})};}
test('global tables authenticate and use only the current workspace',async()=>{for(const table of ['customers','accounts','funds','holdings','applications'])for(const source of ['draft','formal']){const f=fixture();const r=await f.repo.listTable(token,{table,source});assert.equal(r.total,0);const reads=f.calls.filter(c=>!c.sql.includes('platform_sessions'));assert.equal(reads.length,2);for(const c of reads){assert.equal(c.values[0],37);assert.match(c.sql,/WHERE t.workspace_id=\?/);assert.doesNotMatch(c.sql,/UPDATE|INSERT|DELETE/);}}});
test('search is bound and literal wildcard characters are escaped',async()=>{const f=fixture();await f.repo.listTable(token,{table:'applications',q:"%_' OR 1=1"});for(const c of f.calls.slice(1)){assert.doesNotMatch(c.sql,/OR 1=1/);assert.ok(c.values.slice(1).every(v=>v.startsWith('%\\%\\_')));assert.match(c.sql,/CAST\(v.record_json AS CHAR\) LIKE \?/);}});
test('rows retain decimals and nulls, protocols become readable columns without internal IDs',async()=>{const f=fixture([{chatId:'chat',caseId:'case',project:'项目',name:'客户',simulated_balance:'100.00',record_json:JSON.stringify({CertificateNo:'TEST',ApplicationAmount:'100.00'}),available_volume:null}]);const result=await f.repo.listTable(token,{table:'applications'});assert.equal(result.rows[0].ApplicationAmount,'100.00');assert.equal(result.rows[0].available_volume,null);assert.ok(result.columns.some(c=>c.label==='投资人证件号码'));assert.ok(!result.columns.some(c=>['chatId','caseId','record_json'].includes(c.key)));});
test('invalid table, pagination and query length cannot be interpolated',()=>{for(const input of [{table:'accounts;DROP'},{source:'all'},{offset:-1},{offset:1.5},{limit:201},{limit:0},{q:'a'.repeat(201)}])assert.throws(()=>catalogOptions(input),{code:'INVALID_CATALOG_QUERY'});});
test('mixed historical and protocol-backed customers retain real names, type and branch per row',async()=>{const f=fixture([{name:'旧客户',investor_type:'1',account_no:'OLDACCOUNT',branch_code:'306',record_json:null},{name:'新客户',investor_type:'0',account_no:'NEWACCOUNT',branch_code:'307',record_json:{InvestorName:'新客户协议户名',IndividualOrInstitution:'0',TransactionAccountID:'NEWACCOUNT',BranchCode:'307',CertificateNo:'REAL-CERT'}}]);const result=await f.repo.listTable(token,{table:'accounts'});assert.equal(result.rows[0].InvestorName,'旧客户');assert.equal(result.rows[0].IndividualOrInstitution,'1');assert.equal(result.rows[0].TransactionAccountID,'OLDACCOUNT');assert.equal(result.rows[0].BranchCode,'306');assert.equal(result.rows[0].CertificateNo,undefined);assert.equal(result.rows[1].InvestorName,'新客户协议户名');assert.ok(result.columns.some(c=>c.key==='InvestorName'));assert.ok(!result.columns.some(c=>c.key==='name'));});
test('joined holding account and customer columns are searchable without exposing nested-only fields',async()=>{const holding=fixture();await holding.repo.listTable(token,{table:'holdings',source:'draft',q:'ACCOUNT'});for(const c of holding.calls.slice(1)){assert.match(c.sql,/CAST\(v.`account_no` AS CHAR\) LIKE \?/);assert.match(c.sql,/CAST\(v.`customer_name` AS CHAR\) LIKE \?/);}const customer=fixture();await customer.repo.listTable(token,{table:'customers',q:'NAME'});for(const c of customer.calls.slice(1)){assert.doesNotMatch(c.sql,/CAST\(v.`account_no` AS CHAR\)/);assert.match(c.sql,/CAST\(v.`name` AS CHAR\) LIKE \?/);}});
