import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import mysql from 'mysql2/promise';
import {migrationConfig} from '../src/migrate.js';
import {createCaseRepository,sessionTokenHash} from '../src/index.js';
import {planContract} from '../../case-agent/test/plan-contract-fixture.js';
import {exchangePlan} from '../../case-agent/test/exchange-plan-fixture.js';
import {createDataGenerationGraph} from '../../case-agent/src/data-generation.js';

test('MySQL: same-version dual confirmation freezes drafts, survives retries and never applies formal data',
 {skip:process.env.CASE_CONFIRMATION_MYSQL!=='1'},async()=>{
 const db=await mysql.createConnection(migrationConfig());
 try{
  await db.beginTransaction();
  const token=crypto.randomBytes(32).toString('base64url'),id=crypto.randomUUID();
  const [user]=await db.execute(`INSERT INTO platform_users(public_id,email,password_hash,display_name) VALUES (?,?,?,'Plan测试')`,[id,id+'@example.invalid','synthetic']);
  const [workspace]=await db.execute('INSERT INTO workspaces(public_id,owner_user_id) VALUES (?,?)',[crypto.randomUUID(),user.insertId]);
  await db.execute('INSERT INTO platform_sessions(token_hash,user_id,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))',[sessionTokenHash(token),user.insertId]);
  let n=0;
  const transaction=async action=>{const name='plan_'+ ++n;await db.query('SAVEPOINT '+name);try{return await action(db);}catch(e){await db.query('ROLLBACK TO SAVEPOINT '+name);throw e;}};
  const repo=createCaseRepository({transaction});
  const chat=await repo.createChat(token,'双确认测试'),item=await repo.createCase(token,chat.publicId,'测试Case');
  const args=[token,chat.publicId,item.publicId];
  const plan={objective:'申购结果验证',preconditions:[],scenarios:[{title:'申购',setup:'合成客户',action:'申购100元',expected:'状态CONFIRMED',evidence:'TA确认'}],openQuestions:[],exchangePlan};
  plan.contract=planContract(plan);
  await repo.saveSopProposal(...args,plan);
  await assert.rejects(repo.confirmSopProposal(...args,1,'EXPECTATIONS'),{code:'PLAN_DATA_CONFIRMATION_REQUIRED'});
  await repo.confirmSopProposal(...args,1,'DATA');
  await repo.confirmSopProposal(...args,1,'DATA');
  assert.deepEqual((await repo.getLatestSopProposal(...args)).confirmations.map(c=>c.section),['DATA']);
  const before=await repo.generatedData(...args);assert.equal(before.status,'NOT_STARTED');
  const noFiles=await repo.createCase(token,chat.publicId,'无需文件交换的计算场景');
  const noFileArgs=[token,chat.publicId,noFiles.publicId];
  const noFilePlan=structuredClone(plan);
  noFilePlan.exchangePlan={status:'NOT_REQUIRED',steps:[],openQuestions:[]};
  noFilePlan.contract.dataSpecification={customers:[],accounts:[],funds:[],holdings:[],missing:[]};
  noFilePlan.contract.applications=[]; noFilePlan.contract.expectations=[];
  noFilePlan.contract.missing=['现有预期字段不支持该计算结果'];
  await repo.saveSopProposal(...noFileArgs,noFilePlan);
  await repo.confirmSopProposal(...noFileArgs,1,'DATA');
  assert.deepEqual((await repo.getLatestSopProposal(...noFileArgs)).confirmations.map(c=>c.section),['DATA']);
  await assert.rejects(repo.confirmSopProposal(...noFileArgs,1,'EXPECTATIONS'),{code:'PLAN_HAS_OPEN_QUESTIONS'});
  assert.equal((await repo.generatedData(...noFileArgs)).status,'NOT_STARTED');
  const unsupported=structuredClone(noFilePlan);
  unsupported.scenarios[0].expected='营业网点编号10001';
  unsupported.contract.missing=[];
  unsupported.contract.expectations=[{scenarioIndex:0,expectedQuote:'营业网点编号10001',source:'FORMAL_ACCOUNT',selector:{accountIndex:null,transactionAccountId:'90000000000000001',channelId:null,fundCode:null,shareClass:null,fileType:null,businessDate:null},field:'branchCode',operator:'eq',expectedValue:'10001'}];
  await repo.saveSopProposal(...noFileArgs,unsupported);
  await repo.confirmSopProposal(...noFileArgs,2,'DATA');
  await assert.rejects(repo.confirmSopProposal(...noFileArgs,2,'EXPECTATIONS'),{code:'NO_EXCHANGE_WORKFLOW_UNSUPPORTED'});
  const reviewedCase=await repo.createCase(token,chat.publicId,'业务预期审阅');
  const reviewedArgs=[token,chat.publicId,reviewedCase.publicId];
  const reviewed=structuredClone(noFilePlan);
  reviewed.scenarios[0].expected='字段变化后按用户规则返回结果';
  reviewed.contract={...reviewed.contract,version:2,missing:[],businessExpectations:[{scenarioIndex:0,expectedQuote:reviewed.scenarios[0].expected}]};
  await repo.saveSopProposal(...reviewedArgs,reviewed);
  await assert.rejects(repo.confirmSopProposal(...reviewedArgs,1,'EXPECTATIONS'),{code:'PLAN_DATA_CONFIRMATION_REQUIRED'});
  await repo.confirmSopProposal(...reviewedArgs,1,'DATA');
  await repo.confirmSopProposal(...reviewedArgs,1,'EXPECTATIONS');
  assert.equal((await repo.getLatestSopProposal(...reviewedArgs)).status,'LOCKED');
  assert.equal((await repo.generatedData(...reviewedArgs)).status,'NOT_STARTED');
  const blockedCase=await repo.createCase(token,chat.publicId,'模拟账户不能跳过文件');
  const blockedArgs=[token,chat.publicId,blockedCase.publicId];
  const blockedPlan=structuredClone(reviewed);blockedPlan.contract.dataSpecification.customers=[plan.contract.dataSpecification.customers[0]];blockedPlan.contract.dataSpecification.funds=plan.contract.dataSpecification.funds;blockedPlan.contract.dataSpecification.accounts=[{customerIndex:0,branchCode:'306'}];
  await repo.saveSopProposal(...blockedArgs,blockedPlan);
  await assert.rejects(repo.confirmSopProposal(...blockedArgs,1,'DATA'),{code:'DATA_EXCHANGE_REQUIRED'});
  assert.deepEqual((await repo.getLatestSopProposal(...blockedArgs)).confirmations,[]);
  assert.equal((await repo.generatedData(...blockedArgs)).status,'NOT_STARTED');
  const unplanned=structuredClone(noFilePlan);
  unplanned.exchangePlan={status:'UNPLANNED',steps:[],openQuestions:['需要明确文件时间']};
  await repo.saveSopProposal(...noFileArgs,unplanned);
  await assert.rejects(repo.confirmSopProposal(...noFileArgs,3,'DATA'),{code:'EXCHANGE_PLAN_REQUIRED'});

  const changed=structuredClone(plan);changed.contract.dataSpecification.customers[0].simulatedBalance='2000.00';
  await repo.saveSopProposal(...args,changed);
  await assert.rejects(repo.confirmSopProposal(...args,1,'EXPECTATIONS'),{code:'STALE_PLAN'});
  assert.deepEqual((await repo.getLatestSopProposal(...args)).confirmations,[]);
  await assert.rejects(repo.confirmSopProposal(...args,2,'EXPECTATIONS'),{code:'PLAN_DATA_CONFIRMATION_REQUIRED'});
  await repo.confirmSopProposal(...args,2,'DATA');
  await repo.confirmSopProposal(...args,2,'EXPECTATIONS');
  const spec=changed.contract.dataSpecification;
  await assert.rejects(repo.executeGeneratedData(...args,2,plan.contract.dataSpecification,()=>{}),{code:'PLAN_DATA_MISMATCH'});
  const run=(db,scope,specification)=>createDataGenerationGraph({db,scope,specification}).invoke({});
  await repo.executeGeneratedData(...args,2,spec,run);
  assert.equal((await repo.executeGeneratedData(...args,2,spec,run)).replayed,true);
  const generated=await repo.generatedData(...args);
  assert.equal(generated.customers[0].simulated_balance,'2000.00');
  assert.equal(generated.planDataFrozen,true);
  await assert.rejects(repo.editGeneratedData(...args,{revision:0,changes:{customers:[],accounts:[],funds:[],holdings:[]}}),{code:'PLAN_DATA_FROZEN'});
  await repo.confirmGeneratedData(...args,0);
  const [[formal]]=await db.execute('SELECT COUNT(*) AS n FROM sales_confirmed_accounts WHERE workspace_id=?',[workspace.insertId]);assert.equal(Number(formal.n),0);
  const [[holds]]=await db.execute('SELECT COUNT(*) AS n FROM sales_confirmed_holdings WHERE workspace_id=?',[workspace.insertId]);assert.equal(Number(holds.n),0);
  await assert.rejects(repo.saveSopProposal(...args,plan),{code:'INVALID_CASE_STATE'});
  const foreign=await repo.createChat(token,'另一Chat');
  await assert.rejects(repo.getLatestSopProposal(token,foreign.publicId,item.publicId),{code:'CASE_NOT_FOUND'});
 }finally{await db.rollback();await db.end();}
});
