import React,{useEffect,useState} from 'react';
import {Search,RefreshCw,ChevronLeft,ChevronRight,Download} from 'lucide-react';
import {requestCase} from './live-case-api.js';
import './global-catalog.css';
const downloadUrl=file=>'/live-api/files/catalog/download?'+new URLSearchParams({kind:file.kind,id:file.locator,fileName:file.fileName});
export function GlobalFileCatalog({onOpenCase}){
 const [search,setSearch]=useState(''),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[tick,setTick]=useState(0),[state,setState]=useState({loading:true,data:null,error:''});
 useEffect(()=>{const t=setTimeout(()=>{setQ(search.trim());setOffset(0);},250);return()=>clearTimeout(t);},[search]);
 useEffect(()=>{let active=true;setState({loading:true,data:null,error:''});requestCase(`/files/catalog?q=${encodeURIComponent(q)}&offset=${offset}&limit=100`).then(data=>{if(active)setState({loading:false,data,error:''});}).catch(error=>{if(active)setState({loading:false,data:null,error:error.message});});return()=>{active=false;};},[q,offset,tick]);
 const data=state.data;
 return <section className="gc-page" aria-labelledby="gc-files-title"><header className="gc-header"><h1 id="gc-files-title">文件</h1><button className="gc-icon" aria-label="刷新文件" disabled={state.loading} onClick={()=>setTick(tick+1)}><RefreshCw size={16}/></button></header><div className="gc-toolbar"><label className="gc-search"><Search size={16}/><input aria-label="搜索文件" placeholder="搜索" maxLength={200} value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {state.error?<div className="gc-empty" role="alert"><p>{state.error}</p><button onClick={()=>setTick(tick+1)}>重试</button></div>:state.loading?<p className="gc-empty" role="status">正在读取…</p>:!data?.files.length?<p className="gc-empty">暂无文件。</p>:<div className="gc-table-scroll" tabIndex={0} role="region" aria-label="文件记录，可横向和纵向滚动"><table><caption className="cw-sr-only">账户内的申请与回传文件</caption><thead><tr>{['文件名称','文件类型','方向','项目','Case','通道','文件大小','时间','操作'].map(label=><th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{data.files.map((file,i)=><tr key={`${file.kind}-${file.locator}-${file.fileName}-${i}`}><td className="gc-file-name">{file.fileName}</td><td>{file.fileType}</td><td>{file.direction==='OUTBOUND'?'申请文件':'TA回传'}</td><td>{file.project||'—'}</td><td>{file.caseTitle||'—'}</td><td>{file.channelName||'—'}</td><td>{Number(file.byteLength).toLocaleString()} 字节</td><td>{file.createdAt?new Date(file.createdAt).toLocaleString('zh-CN'):'—'}</td><td><a href={downloadUrl(file)} download={file.fileName} aria-label={`下载 ${file.fileName}`}><Download size={14}/> 下载</a>{onOpenCase&&file.caseId&&<button onClick={()=>onOpenCase(file.chatId,file.caseId)}>查看 Case</button>}</td></tr>)}</tbody></table></div>}
 <footer className="gc-pagination"><button aria-label="上一页" disabled={state.loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}><ChevronLeft size={16}/></button><span>{Math.floor(offset/100)+1}</span><button aria-label="下一页" disabled={state.loading||!data||offset+data.files.length>=data.total} onClick={()=>setOffset(offset+100)}><ChevronRight size={16}/></button></footer></section>;
}
