import React,{useEffect,useState} from 'react';
import {Search,RefreshCw,ChevronLeft,ChevronRight} from 'lucide-react';
import {requestCase} from './live-case-api.js';
import './global-catalog.css';
const tables=[['customers','客户'],['accounts','账户'],['funds','基金'],['holdings','持仓'],['applications','申请记录']];
const labels={READY:'待生成',BATCHED:'已合批',GENERATED:'已生成',DELIVERED:'已发送',WAITING_RETURN:'等待回传',CONFIRMED:'已确认',FAILED:'失败',CANCELED:'已取消'};
export function catalogCell(key,value){if(value===null||value===undefined||value==='')return '—';if(key==='status')return labels[value]??'待处理';if(['investor_type','IndividualOrInstitution'].includes(key))return String(value)==='1'?'个人':'机构';if(typeof value==='object')return JSON.stringify(value);return String(value);}
export function GlobalDataCatalog({onOpenCase}){
 const [table,setTable]=useState(tables.some(([key])=>key===new URLSearchParams(location.search).get('dataTable'))?new URLSearchParams(location.search).get('dataTable'):'customers'),[source,setSource]=useState('draft'),[search,setSearch]=useState(''),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[tick,setTick]=useState(0),[state,setState]=useState({loading:true,data:null,error:''});
 useEffect(()=>{const timer=setTimeout(()=>{setQ(search.trim());setOffset(0);},250);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{let active=true;setState({loading:true,data:null,error:''});requestCase(`/data/tables/${table}?source=${source}&q=${encodeURIComponent(q)}&offset=${offset}&limit=100`).then(data=>{if(active)setState({loading:false,data,error:''});}).catch(error=>{if(active)setState({loading:false,data:null,error:error.message});});return()=>{active=false;};},[table,source,q,offset,tick]);
 const data=state.data,title=tables.find(([key])=>key===table)?.[1]||'客户';
 return <section className="gc-page" aria-labelledby="gc-title"><header className="gc-header"><h1 id="gc-title">数据</h1><button className="gc-icon" aria-label="刷新数据" disabled={state.loading} onClick={()=>setTick(tick+1)}><RefreshCw size={16}/></button></header>
 <nav className="gc-tabs" aria-label="数据表">{tables.map(([key,label])=><button key={key} aria-current={table===key?'page':undefined} onClick={()=>{setTable(key);setOffset(0);const url=new URL(location.href);url.searchParams.set('dataTable',key);history.replaceState(null,'',url);}}>{label}</button>)}</nav>
 <div className="gc-toolbar"><label className="gc-search"><Search size={16}/><input aria-label={`搜索${title}`} placeholder="搜索" value={search} maxLength={200} onChange={e=>setSearch(e.target.value)}/></label>{!['funds','applications'].includes(table)&&<select aria-label="数据来源" value={source} onChange={e=>{setSource(e.target.value);setOffset(0);}}><option value="draft">草稿</option><option value="formal">正式数据</option></select>}</div>
 {state.error?<div className="gc-empty" role="alert"><p>{state.error}</p><button onClick={()=>setTick(tick+1)}>重试</button></div>:state.loading?<p className="gc-empty" role="status">正在读取…</p>:!data?.rows.length?<p className="gc-empty">暂无{title}记录。</p>:<div className="gc-table-scroll" tabIndex={0} role="region" aria-label={`${title}记录，可横向和纵向滚动`}><table><caption className="cw-sr-only">{title}记录</caption><thead><tr>{data.columns.map(col=><th key={col.key} scope="col">{col.label}</th>)}{onOpenCase&&<th scope="col">来源</th>}</tr></thead><tbody>{data.rows.map((row,i)=><tr key={offset+i}>{data.columns.map(col=><td key={col.key} title={catalogCell(col.key,row[col.key])}>{catalogCell(col.key,row[col.key])}</td>)}{onOpenCase&&<td>{row.chatId&&row.caseId?<button onClick={()=>onOpenCase(row.chatId,row.caseId)}>查看 Case</button>:'—'}</td>}</tr>)}</tbody></table></div>}
 <footer className="gc-pagination"><button aria-label="上一页" disabled={state.loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}><ChevronLeft size={16}/></button><span>{Math.floor(offset/100)+1}</span><button aria-label="下一页" disabled={state.loading||!data||offset+data.rows.length>=data.total} onClick={()=>setOffset(offset+100)}><ChevronRight size={16}/></button></footer></section>;
}
